# Generated by Django 4.2.1 on 2023-05-30 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_chamados', models.IntegerField()),
                ('qtd_registrados', models.IntegerField()),
                ('positivos', models.IntegerField()),
                ('negativos', models.IntegerField()),
                ('data', models.DateField()),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analisedados.atendente')),
            ],
        ),
    ]
